version: "3.1"

services:
  db:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - 8080:8080
    volumes:
      - ./:/usr/app
    command: go env -w GO111MODULE=auto && air
volumes:
  data:
